export  const originList = [
    "All",
    "France",
    "USA",
    "UK",
    "Australia",
    "Japan",
    "Latvia",
    "Spain",
    "Germany",
    "Thailand",
    "Ukraine",
    "Poland",
    "Russia",
    "New Zealand",
    "Canada",
    "Italy",
    "Switzerland",
    "Belgium",
    "Portugal",
    "Bulgaria",
    "Turkey",
    "Belarus",
    "Denmark",
    "Hungary",
    "Austria",
    "Estonia",
    "Norway",
    "Israel",
    "Netherlands",
    "Romania",
    "Mexico",
    "Slovenia",
    "China",
    "Sweden",
    "Colombia",
    "Chile",
    "Czech Republic",
    "Lithuania",
    "Ireland",
    "Greece",
    "Monaco"
]

export const tagList = [
    "Swimwear",
    "Lingerie",
    "Clothes",
    "Lounge",
    "Corsets",
    "Accessories",
    "Hosiery",
    "BDSM",
    "Men",
    "Shapewear",
    "Dress Up",
    "Sport",
    "Jewelry",
    "Bridal",
    "Leakproof",
    "Maternity",
    "Surgery",
    "Thermal",
    "Shoes",
    "Kids",
    "Stick-on",
    "Resortwear"
]

export const sizeList = [
    "All",
    "Tailored",
    "Small cup",
    "Large cup",
    "Bespoke"
]